version: "3.7"

services:
  traefik:
    container_name: traefik
    image: ${IMAGE}
    restart: unless-stopped
    command:
      #global
      - "--global.sendAnonymousUsage=true"
      # error logs 
      - "--log=true"
      - "--log.level=INFO"
      - "--log.filePath=/logs/traefik.log"
      # access logs
      - "--accessLog=true"
      - "--accessLog.filePath=/logs/access.log"
      - "--accessLog.bufferingSize=100" # Configuring a buffer of 100 lines
      - "--accessLog.filters.statusCodes=204-299,400-499,500-599"
      # api
      - "--api=true"
      - "--api.insecure=false"
      - "--api.dashboard=true" 
      # docker providers: uses docker container tags to enable traefik rules
      #- "--providers.docker=true"
      #- "--providers.docker.exposedbydefault=false"
      #- "--providers.docker.watch"
      # file providers: uses set file for rules
      - "--providers.file.directory=/rules"
      - "--providers.file.watch=true"
      # entrypoints
      #- "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      #- "--entryPoints.traefik.address=:8080"
      # DNS Resolver: CloudFlare 
      #- "--certificatesResolvers.dnsresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.dnsresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.dnsresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.dnsresolver.acme.dnschallenge.delayBeforeCheck=30"
      - "--certificatesresolvers.dnsresolver.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      - "--certificatesresolvers.dnsresolver.acme.email=${CLOUDFLARE_EMAIL}"
      - "--certificatesresolvers.dnsresolver.acme.storage=/letsencrypt/acme.json"
      #DynDNS Resolver
      #- "--certificatesresolvers.dynresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.dynresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.dynresolver.acme.email=${CLOUDFLARE_EMAIL}"
      - "--certificatesresolvers.dynresolver.acme.storage=/letsencrypt/wmc/acme.json"
      
    ports:
      #- ${LOCAL_IP}:80:80/tcp
      - ${LOCAL_IP}:443:443/tcp
      #- ${LOCAL_IP}:8080:8080/tcp
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/rules:/rules"
      - "./traefik/logs/traefik.log:/logs/traefik.log"
      - "./traefik/logs/access.log:/logs/access.log"
      - "./traefik/shared:/shared"
      - "./traefik/letsencrypt:/letsencrypt"           
    environment:
      - "CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}"
      - "CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}"
      - "DOMAIN=${DOMAIN}"
      - "BASIC_USER_AUTH=${BASIC_USER_AUTH}"
